import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/providers";
import InitUser from "./components/common/InitUser";

export const metadata: Metadata = {
  title: "RAG-POC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <InitUser />
          {children}
        </Providers>
      </body>
    </html>
  );
}